"""Added Password field

Revision ID: 328efe55049f
Revises: 4a94bdf8abe8
Create Date: 2022-05-25 11:19:52.535084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328efe55049f'
down_revision = '4a94bdf8abe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
